// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY0YYtGD32QNx5lWj7YujEngqEMDzmTmI',
    appId: '1:112707544398:web:e947d9f192bd98511eaa1f',
    messagingSenderId: '112707544398',
    projectId: 'fcv-trucker',
    authDomain: 'fcv-trucker.firebaseapp.com',
    storageBucket: 'fcv-trucker.appspot.com',
    measurementId: 'G-W78NFBB21F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM7ir-ssjX9sNXJjycySbHGhuT62o4J70',
    appId: '1:112707544398:android:b4e0325b144851901eaa1f',
    messagingSenderId: '112707544398',
    projectId: 'fcv-trucker',
    storageBucket: 'fcv-trucker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBglUG5BA2qjQJkC4JUZqflaDPLkGGdL4',
    appId: '1:112707544398:ios:36745e80cf20408b1eaa1f',
    messagingSenderId: '112707544398',
    projectId: 'fcv-trucker',
    storageBucket: 'fcv-trucker.appspot.com',
    iosClientId: '112707544398-3b69en5okc7v5scd6h0oclbsv57fhgeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcvTrucker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBglUG5BA2qjQJkC4JUZqflaDPLkGGdL4',
    appId: '1:112707544398:ios:36745e80cf20408b1eaa1f',
    messagingSenderId: '112707544398',
    projectId: 'fcv-trucker',
    storageBucket: 'fcv-trucker.appspot.com',
    iosClientId: '112707544398-3b69en5okc7v5scd6h0oclbsv57fhgeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcvTrucker',
  );
}
